# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [50]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np
# Let's define a one-dimensional array 
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [51]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [52]:
type(my_numpy_array)

numpy.ndarray

In [53]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8], [7, 3, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [54]:
matrix_2  = np.array([[3,7,9,3], [4,3,2,2]])
matrix_2

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [55]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)
x

array([0.41453541, 0.05843575, 0.63884177, 0.11845611, 0.08170277,
       0.7252672 , 0.75586567, 0.30314655, 0.70437585, 0.4754233 ,
       0.97420728, 0.69642981, 0.34494584, 0.25178104, 0.27630109,
       0.17953263, 0.98061314, 0.89273142, 0.15561691, 0.29553295])

In [56]:
# you can create a matrix of random number as well
x = np.random.rand(3,3)
x

array([[0.07855192, 0.68633378, 0.11260265],
       [0.76695352, 0.59482138, 0.43709331],
       [0.0194963 , 0.69407932, 0.33459112]])

In [57]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)
x

6

In [58]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)
x

array([39, 46, 49, 98, 50, 61, 78, 19, 77, 66, 49, 84, 37, 23, 77])

In [59]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [60]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [61]:
# Matrix of ones
x = np.ones((7,7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [62]:
# Array of zeros
x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [63]:
x = int(input("Please input a positive intger value"))
x = np.random.randint(1, x, 10)
x

Please input a positive intger value10


array([5, 8, 2, 8, 1, 5, 2, 5, 3, 7])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [64]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
y = np.arange(1,10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# Add 2 numpy arrays together
sum  = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [67]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [68]:
sqrt = np.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [69]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [70]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
dist = np.sqrt(X**2 + Y**2)
dist

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [71]:
my_np_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_np_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [72]:
# Access specific index from the numpy array
my_np_array[1]

5

In [73]:
# Starting from the first index 0 up until and NOT including the last element
my_np_array[0:-1]

array([ 3,  5,  6,  2,  8, 10, 20])

In [74]:
# Broadcasting, altering several values in a numpy array at once
my_np_array[0:4] = 7
my_np_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [75]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1,10, (4,4))
matrix

array([[9, 8, 3, 6],
       [3, 9, 4, 9],
       [4, 5, 5, 6],
       [9, 5, 2, 9]])

In [76]:
# Get a row from a mtrix
matrix[1,]

array([3, 9, 4, 9])

In [77]:
# Get one element
matrix[1][2]

4

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [78]:
X = np.array([[2, 30, 20, -2, -4],
             [3, 4, 40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])

In [79]:
X[-1] = 0
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [80]:
matrix = np.random.randint(1, 10, (5,5))
matrix

array([[6, 8, 7, 4, 3],
       [3, 7, 3, 5, 3],
       [3, 3, 8, 1, 5],
       [2, 5, 1, 6, 9],
       [9, 3, 2, 5, 3]])

In [81]:
new_matrix = matrix[matrix > 7]
new_matrix

array([8, 8, 9, 9])

In [82]:
# Obtain odd elements only
odd_matrix = matrix[matrix%2 == 1]
odd_matrix

array([7, 3, 3, 7, 3, 5, 3, 3, 3, 1, 5, 5, 1, 9, 9, 3, 5, 3])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [83]:
X = np.array([[2, 30, 20, -2, -4],
             [3, 4, 40, -3, -2],
             [-3, 4, -6, 90, 10],
             [25, 45, 34, 22, 12],
             [13, 24, 22, 32, 37]])
X

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [84]:
X[X < 0] = 0
X

array([[ 2, 30, 20,  0,  0],
       [ 3,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [85]:
X[X%2 == 1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [86]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [87]:
import pandas as pd

In [88]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({'Bank Client ID': [111,222,333,444],
                              'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                              'Net Worth [$]': [3500, 29000, 10000, 2000],
                              'Years with bank': [3,4,9,5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [89]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [90]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4

In [91]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [92]:
portfolio_df = pd.DataFrame({'Stock ticker': ['AAPL', 'AMZN', 'GOOGL'],
                            'Number of shares': [15787154000, 10250000000, 12781000000],
                            'Price per share': [179.46, 140.57, 131.33]})
portfolio_df

Stock ticker  Number of shares  Price per share
0         AAPL       15787154000           179.46
1         AMZN       10250000000           140.57
2        GOOGL       12781000000           131.33

In [93]:
stock_value = portfolio_df["Price per share"]*portfolio_df['Number of shares']
stock_value.sum()

5952533886840.0

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [94]:
!pip install lxml
!python -m pip install --upgrade pip

In [95]:
# Pandas is used to read a csv file and store data in a DataFrame


In [96]:
# Read tabular data using read_html
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1045)>

In [97]:
house_price_df[1]

NameError: name 'house_price_df' is not defined

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
retirement_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_df[0]

# TASK #8: PANDAS OPERATIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank Client ID': [111,222,333,444],
                              'Bank Client Name': ['Chanel', 'Steve', 'Mitch', 'Ryan'],
                              'Net Worth [$]': [3500, 29000, 10000, 2000],
                              'Years with bank': [3,4,9,5]})
bank_client_df

In [ ]:
# Pick certain rows that satisfy a certain criteria 
df_loyal = bank_client_df[bank_client_df['Years with bank'] >= 5]
df_loyal

In [ ]:
# Delete a column from a DataFrame
del bank_client_df['Bank Client ID']
bank_client_df

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[bank_client_df['Net Worth [$]'] >= 5000]
df_high_networth

In [ ]:
sum_networth = df_high_networth['Net Worth [$]'].sum()
sum_networth

# TASK #9: PANDAS WITH FUNCTIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def networth_update(balance):
    return balance*1.2

In [ ]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(networth_update)

In [ ]:
bank_client_df['Bank Client Name'].apply(len)

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def triple(price):
    return price*3+200

In [ ]:
result = bank_client_df['Net worth [$]'].apply(triple)
result

In [ ]:
result.sum()

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank')

In [ ]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True
bank_client_df.sort_values( by = 'Years with bank', inplace = True)
bank_client_df

In [ ]:
# Set inplace = True to ensure that change has taken place in memory 


In [98]:
# Note that now the change (ordering) took place 


# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [99]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [100]:
df1 = pd.DataFrame({ 'A': ['A0', 'A1', 'A2', 'A3'],
                   'B': ['B0', 'B1', 'B2', 'B3'],
                   'C': ['C0', 'C1', 'C2', 'C3'],
                   'D': ['D0', 'D1', 'D2', 'D3']},
                  index = [0,1,2,3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [101]:
df2 = pd.DataFrame({ 'A': ['A4', 'A5', 'A6', 'A7'],
                   'B': ['B4', 'B5', 'B6', 'B7'],
                   'C': ['C4', 'C5', 'C6', 'C7'],
                   'D': ['D4', 'D5', 'D6', 'D7']},
                  index = [0,1,2,3])
df2

A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [102]:
df3 = pd.DataFrame({ 'A': ['A8', 'A9', 'A10', 'A11'],
                   'B': ['B8', 'B9', 'B10', 'B11'],
                   'C': ['C8', 'C9', 'C10', 'C11'],
                   'D': ['D8', 'D9', 'D10', 'D11']},
                  index = [0,1,2,3])
df3

A    B    C    D
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

In [103]:
pd.concat([df1, df2, df3])

A    B    C    D
0   A0   B0   C0   D0
1   A1   B1   C1   D1
2   A2   B2   C2   D2
3   A3   B3   C3   D3
0   A4   B4   C4   D4
1   A5   B5   C5   D5
2   A6   B6   C6   D6
3   A7   B7   C7   D7
0   A8   B8   C8   D8
1   A9   B9   C9   D9
2  A10  B10  C10  D10
3  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [104]:
raw_data = { 'Bank Client ID': ['1','2','3','4','5'],
           'First Name': ['Nancy','Alex','Shep','Max','Allen'],
           'Last Name': ['Rob','Ali','George','Mitch','Steve']}
Bank_df1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name','Last Name'])
Bank_df1

Bank Client ID First Name Last Name
0              1      Nancy       Rob
1              2       Alex       Ali
2              3       Shep    George
3              4        Max     Mitch
4              5      Allen     Steve

In [119]:
raw_data = { 'Bank Client ID': ['6','7','8','9','10'],
           'First Name': ['Bill','Dina','Sarah','Heather','Holly'],
           'Last Name': ['Christian','Mo','Steve','Rob','Michelle']}
Bank_df2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name','Last Name'])
Bank_df2

Bank Client ID First Name  Last Name
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Rob
4             10      Holly   Michelle

In [121]:
raw_data = { 'Bank Client ID': ['1','2','3','4','5','6','7','8','9','10'],
           'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'Annual Salary [$/year]'])
bank_df_salary

Bank Client ID  Annual Salary [$/year]
0              1                   25000
1              2                   35000
2              3                   45000
3              4                   48000
4              5                   49000
5              6                   32000
6              7                   33000
7              8                   34000
8              9                   23000
9             10                   22000

In [125]:
bank_df_all = pd.concat([Bank_df1, Bank_df2])
bank_df_all

Bank Client ID First Name  Last Name
0              1      Nancy        Rob
1              2       Alex        Ali
2              3       Shep     George
3              4        Max      Mitch
4              5      Allen      Steve
0              6       Bill  Christian
1              7       Dina         Mo
2              8      Sarah      Steve
3              9    Heather        Rob
4             10      Holly   Michelle

In [126]:
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Rob                   23000
9             10      Holly   Michelle                   22000

In [127]:
new_client = { 'Bank Client ID': ['11'],
             'First Name': ['Ryan'],
             'Last Name': ['Ahmed'],
             'Annual Salary [$/year]': [5000]}
new_client_df = pd.DataFrame(new_client)

Bank Client ID First Name Last Name  Annual Salary [$/year]
0             11       Ryan     Ahmed                    5000

In [131]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df

Bank Client ID First Name  Last Name  Annual Salary [$/year]
0              1      Nancy        Rob                   25000
1              2       Alex        Ali                   35000
2              3       Shep     George                   45000
3              4        Max      Mitch                   48000
4              5      Allen      Steve                   49000
5              6       Bill  Christian                   32000
6              7       Dina         Mo                   33000
7              8      Sarah      Steve                   34000
8              9    Heather        Rob                   23000
9             10      Holly   Michelle                   22000
0             11       Ryan      Ahmed                    5000